# Use postgres/example user/password credentials
version: "3.8"

services:
  postgres_database:
    image: postgres
    restart: always
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: volt_dev
